--
-- This is file `inline.x.lua',
-- generated with the docstrip utility.
--
-- The original source files were:
--
-- inline.dtx  (with options: `lua')
-- 
-- inline --- code inlined in a LuaLaTeX document.
-- version: v0.1a
-- date: 2022/02/06
-- url: https:github.com/jlaurens/inline
-- E-mail: jerome.laurens@u-bourgogne.fr
-- Released under the LaTeX Project Public License v1.3c or later
-- See http://www.latex-project.org/lppl.txt
-- 
