--
-- This is file `track-util.lua',
-- generated with the docstrip utility.
--
-- The original source files were:
--
-- track.dtx  (with options: `lua')
-- 
-- track --- code inlined in a LuaLaTeX document.
-- version: v2.6a
-- date: 2020-11-23
-- url: https:github.com/jlaurens/coder
-- E-mail: jerome.laurens@u-bourgogne.fr
-- Released under the LaTeX Project Public License v1.3c or later
-- See http://www.latex-project.org/lppl.txt
-- 
